### ISSUE TITLE
socket files; plugin dir

### ISSUE THREAD

**Issue by johnbelamaric** [infobloxopen/docker-infoblox#5]
Is there any way to automatically create the plugin dir and to cleanup the socket files?

**Comment by yuewko** [comment]
Yes. It is done using the shell script wrapper (at least for rm socket file) for now, which I thought is more appropriate.
I'm open to doing inside the driver if you so incline.

**Comment by johnbelamaric** [comment]
I see. I don't know, it seems like most containers can be run directly, so that is why I thought perhaps it should change. I wouldn't want our run/deployment to be different than the norm.

On Feb 12, 2016, at 2:15 PM, yuewko <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. It is done using the shell script wrapper (at least for rm socket file) for now, which I thought is more appropriate.
I'm open to doing inside the driver if you so incline.

**Comment by yuewko** [comment]
In which case, I propose adding the following options:

-plugin-dir (default to /run/docker/plugins)
-plugin-name (default to Infoblox)

The socket created will be, by default /run/docker/plugins/Infoblox.sock
The code will make sure /run/docker/plugins exists and will delete /run/docker/plugins/infoblox.sock if exists.

**Comment by johnbelamaric** [comment]
Ok. Should that be "plugin_name" or "driver_name"? I think either works but since it's "--ipam-driver" on the network create side, using "driver_name" may be clearer.

**Comment by yuewko** [comment]
Good point. So,
--plugin-dir
--driver-name

Obviously, that replace -socket.

**Comment by yuewko** [comment]
Fixed by pull request: https://github.com/infobloxopen/docker-infoblox/pull/9
